import { db } from "@Sentinel360/db";
import { alert, notification } from "@Sentinel360/db/schema/alerts";
import { user } from "@Sentinel360/db/schema/auth";
import { caseEvidence, caseIncident, incident, investigationCase } from "@Sentinel360/db/schema/cases";
import { mediaAsset } from "@Sentinel360/db/schema/evidence";
import { role, userRole } from "@Sentinel360/db/schema/rbac";
import { and, eq, inArray } from "drizzle-orm";

import { insertCaseWithGeneratedNumber } from "./case-number";
import { recordCaseEvent } from "./case-timeline";
import { recordAuditEvent } from "./audit-log";
import { EVIDENCE_ENTITY_TYPE, recordCustodyEvent, sha256Hex } from "./chain-of-custody";
import { deleteEvidenceFile, uploadEvidenceFile } from "./evidence-storage";

// Event types the apps/ai CCTV pipeline can report. WATCHLIST_MATCH and
// PLATE_MATCH are declared now so the payload shape doesn't need to change
// once face/ALPR matching lands (see tasks #9/#10) — ingestAiEvent already
// handles them, it just has nothing extra to attach to the case yet.
// ANOMALY_DETECTED comes from the SlowFast model, which the model team flags
// as uncalibrated — apps/ai sends metadata.modelStatus = "experimental".
export const AI_EVENT_TYPES = [
  "WEAPON_DETECTED",
  "ANOMALY_DETECTED",
  "ALTERCATION",
  "WATCHLIST_MATCH",
  "PLATE_MATCH",
] as const;
export type AiEventType = (typeof AI_EVENT_TYPES)[number];

type Severity = "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";

const SEVERITY_BY_EVENT_TYPE: Record<AiEventType, Severity> = {
  WEAPON_DETECTED: "CRITICAL",
  // HIGH rather than CRITICAL: the anomaly model has a known false-positive
  // rate, so it shouldn't outrank a confirmed weapon in the queue.
  ANOMALY_DETECTED: "HIGH",
  ALTERCATION: "HIGH",
  WATCHLIST_MATCH: "HIGH",
  PLATE_MATCH: "MEDIUM",
};

// Roles that should see AI-generated alerts in their inbox. Mirrors the
// role codes routers/alerts.ts#resolveTargetUserIds maps ADMIN/LAW_ENFORCEMENT/
// SECURITY_OPERATOR targetRoles to, minus COMMUNITY (not relevant to an AI
// detection alert).
const AI_ALERT_RECIPIENT_ROLE_CODES = [
  "security_operator",
  "law_enforcement",
  "admin",
  "super_admin",
];

export const AI_MEDIA_KINDS = ["SNAPSHOT", "CROP"] as const;
export const AI_MEDIA_MIME_TYPES = ["image/jpeg", "image/png", "image/webp"] as const;
export const MAX_AI_MEDIA_BYTES = 2 * 1024 * 1024;
const AI_EVIDENCE_SOURCE = "AI_PIPELINE";

const MEDIA_EXTENSION: Record<(typeof AI_MEDIA_MIME_TYPES)[number], string> = {
  "image/jpeg": "jpg",
  "image/png": "png",
  "image/webp": "webp",
};

const MEDIA_TITLE: Record<(typeof AI_MEDIA_KINDS)[number], string> = {
  SNAPSHOT: "AI snapshot",
  CROP: "AI detection close-up",
};

export interface AiEventMedia {
  kind: (typeof AI_MEDIA_KINDS)[number];
  mimeType: (typeof AI_MEDIA_MIME_TYPES)[number];
  dataBase64: string;
}

export interface AiEventInput {
  cameraId: string;
  eventType: AiEventType;
  confidence: number;
  occurredAt: Date;
  // Generated by apps/ai per detection. Makes retries idempotent: the
  // incident number is derived from it, and incident_number is unique.
  eventId?: string;
  summary?: string;
  location?: Record<string, unknown>;
  metadata?: Record<string, unknown>;
  media?: AiEventMedia[];
}

export interface AiEventResult {
  incident: typeof incident.$inferSelect;
  case: typeof investigationCase.$inferSelect;
  alert: typeof alert.$inferSelect | null;
  evidenceIds: string[];
  // True when eventId had already been ingested — nothing new was written.
  duplicate: boolean;
}

async function resolveAiAlertRecipientIds(): Promise<string[]> {
  const rows = await db
    .select({ id: user.id })
    .from(user)
    .innerJoin(userRole, eq(userRole.userId, user.id))
    .innerJoin(role, eq(userRole.roleId, role.id))
    .where(inArray(role.code, AI_ALERT_RECIPIENT_ROLE_CODES));

  return [...new Set(rows.map((r) => r.id))];
}

function incidentNumberFor(eventId: string | undefined): string {
  if (eventId) return `INC-AI-${eventId}`;
  return `INC-AI-${Date.now()}-${Math.random().toString(36).slice(2, 8).toUpperCase()}`;
}

async function findLinkedCase(incidentId: string) {
  const [link] = await db
    .select({ caseId: caseIncident.caseId })
    .from(caseIncident)
    .where(eq(caseIncident.incidentId, incidentId))
    .limit(1);
  if (!link) return null;

  const [linkedCase] = await db
    .select()
    .from(investigationCase)
    .where(eq(investigationCase.id, link.caseId))
    .limit(1);
  return linkedCase ?? null;
}

async function findCaseAlert(caseId: string) {
  const [found] = await db
    .select()
    .from(alert)
    .where(
      and(eq(alert.sourceDomain, "ai_pipeline"), eq(alert.sourceEntityType, "CASE"), eq(alert.sourceEntityId, caseId)),
    )
    .limit(1);
  return found ?? null;
}

async function findCaseEvidenceIds(caseId: string): Promise<string[]> {
  const links = await db
    .select({ id: caseEvidence.evidenceEntityId })
    .from(caseEvidence)
    .where(and(eq(caseEvidence.caseId, caseId), eq(caseEvidence.evidenceEntityType, EVIDENCE_ENTITY_TYPE)));
  return links.map((link) => link.id);
}

interface UploadedAiMedia {
  item: AiEventMedia;
  fileBytes: Buffer;
  fileHash: string;
  originalFilename: string;
  storagePath: string;
}

async function uploadAiMedia(item: AiEventMedia, input: AiEventInput): Promise<UploadedAiMedia> {
  const fileBytes = Buffer.from(item.dataBase64, "base64");
  // Validated before upload: uploadEvidenceFile checks size/type only
  // after the bytes are already in the bucket.
  if (fileBytes.length === 0 || fileBytes.length > MAX_AI_MEDIA_BYTES) {
    throw new Error(`${item.kind} is ${fileBytes.length} bytes (max ${MAX_AI_MEDIA_BYTES})`);
  }
  const originalFilename = `${input.cameraId}-${input.eventType.toLowerCase()}-${item.kind.toLowerCase()}.${MEDIA_EXTENSION[item.mimeType]}`;
  const { storagePath } = await uploadEvidenceFile(fileBytes, originalFilename, item.mimeType);
  return { item, fileBytes, fileHash: sha256Hex(fileBytes), originalFilename, storagePath };
}

/**
 * Stores each image as a READY media_asset linked to the case, with a
 * chain-of-custody CREATED row and an EVIDENCE_LINKED timeline entry — the
 * same rows routers/evidence.ts#create writes for a manual upload, so AI
 * evidence is handled identically downstream. Per-item failures are logged
 * and skipped: losing an image must not lose the alert/docket.
 *
 * Storage uploads run in parallel (the slow part against hosted Supabase),
 * but every DB write stays sequential: recordCaseEvent appends to the
 * hash-chained audit_log by reading the latest hash, so concurrent appends
 * would fork the chain.
 */
async function attachAiEvidence(
  caseId: string,
  input: AiEventInput,
  incidentId: string,
): Promise<string[]> {
  const media = input.media ?? [];
  const uploads = await Promise.allSettled(media.map((item) => uploadAiMedia(item, input)));
  const evidenceIds: string[] = [];

  for (const [index, upload] of uploads.entries()) {
    if (upload.status === "rejected") {
      console.error(`Failed to upload AI ${media[index]?.kind} evidence for case ${caseId}`, upload.reason);
      continue;
    }
    const { item, fileBytes, fileHash, originalFilename, storagePath } = upload.value;
    let recorded = false;

    try {
      const [created] = await db
        .insert(mediaAsset)
        .values({
          type: "IMAGE",
          title: `${MEDIA_TITLE[item.kind]} — ${input.eventType.replace(/_/g, " ").toLowerCase()}`,
          description: `Auto-captured by the AI monitoring pipeline on camera ${input.cameraId} at ${input.occurredAt.toISOString()}.`,
          source: AI_EVIDENCE_SOURCE,
          sourceCameraId: input.cameraId,
          originalFilename,
          mimeType: item.mimeType,
          fileSize: fileBytes.length,
          fileHash,
          storageUrl: storagePath,
          status: "READY",
          metadata: {
            kind: item.kind,
            eventType: input.eventType,
            eventId: input.eventId,
            confidence: input.confidence,
            incidentId,
            ...input.metadata,
          },
          createdByUserId: null,
        })
        .returning();
      if (!created) {
        throw new Error("Evidence record was not created");
      }
      recorded = true;

      await recordCustodyEvent({
        evidenceEntityId: created.id,
        action: "CREATED",
        evidenceHash: fileHash,
        reason: `Auto-captured by AI pipeline (${input.eventType}, camera ${input.cameraId})`,
        location: input.cameraId,
        metadata: { eventId: input.eventId, kind: item.kind, source: AI_EVIDENCE_SOURCE },
      });

      await db.insert(caseEvidence).values({
        caseId,
        evidenceEntityType: EVIDENCE_ENTITY_TYPE,
        evidenceEntityId: created.id,
        relationshipDescription: `${MEDIA_TITLE[item.kind]} from AI detection`,
        createdByUserId: null,
      });

      await recordCaseEvent({
        caseId,
        eventType: "EVIDENCE_LINKED",
        summary: `AI evidence captured: ${created.title} (SHA-256 ${fileHash.slice(0, 12)}…)`,
        payload: { evidenceId: created.id, fileHash, mimeType: item.mimeType, source: AI_EVIDENCE_SOURCE },
        actorUserId: null,
      });

      evidenceIds.push(created.id);
    } catch (error) {
      console.error(`Failed to attach AI ${item.kind} evidence to case ${caseId}`, error);
      if (!recorded) {
        // No media_asset row points at the file, so don't leave it orphaned
        // in the private bucket. Once a row exists the file must stay.
        await deleteEvidenceFile(storagePath);
      }
    }
  }

  return evidenceIds;
}

/**
 * Entry point for apps/ai's POST /internal/ai/events. Writes an incident,
 * auto-opens a case (docket) for it, attaches any snapshot/crop images as
 * evidence, and raises an alert with notification fan-out — the same
 * shapes routers/cases.ts#create and routers/alerts.ts#create use for
 * human-initiated actions, so the resulting rows are indistinguishable to
 * the rest of the app. actorUserId is null throughout: there is no Supabase
 * session on this path, only a shared-secret-authenticated service.
 *
 * Retries with the same eventId return the original case instead of
 * opening a second docket. If an earlier attempt died after creating the
 * incident but before linking a case, the retry resumes from there.
 */
export async function ingestAiEvent(input: AiEventInput): Promise<AiEventResult> {
  const severity = SEVERITY_BY_EVENT_TYPE[input.eventType];
  const title = input.summary ?? `${input.eventType.replace(/_/g, " ")} — camera ${input.cameraId}`;
  const description = `Automatically detected by the AI monitoring pipeline on camera ${input.cameraId} (${(input.confidence * 100).toFixed(0)}% confidence).`;
  const incidentNumber = incidentNumberFor(input.eventId);

  const [insertedIncident] = await db
    .insert(incident)
    .values({
      incidentNumber,
      incidentType: input.eventType,
      title,
      description,
      location: input.location ?? {},
      occurredAt: input.occurredAt,
      severity,
      status: "REPORTED",
      sourceDomain: "ai_pipeline",
      sourceEntityType: "CAMERA",
      sourceEntityId: input.cameraId,
      reportedByUserId: null,
    })
    .onConflictDoNothing({ target: incident.incidentNumber })
    .returning();

  let createdIncident = insertedIncident;
  if (!createdIncident) {
    const [existing] = await db.select().from(incident).where(eq(incident.incidentNumber, incidentNumber)).limit(1);
    if (!existing) {
      throw new Error("Incident was not created");
    }
    const existingCase = await findLinkedCase(existing.id);
    if (existingCase) {
      return {
        incident: existing,
        case: existingCase,
        alert: await findCaseAlert(existingCase.id),
        evidenceIds: await findCaseEvidenceIds(existingCase.id),
        duplicate: true,
      };
    }
    createdIncident = existing;
  }

  const createdCase = await insertCaseWithGeneratedNumber({
    caseType: "AI_GENERATED",
    title: `Auto-docket: ${title}`,
    description,
    priority: severity,
    assignedToUserId: null,
    createdByUserId: null,
  });

  await recordCaseEvent({
    caseId: createdCase.id,
    eventType: "CASE_CREATED",
    summary: `Case ${createdCase.caseNumber} auto-opened by AI pipeline: ${createdCase.title}`,
    payload: { caseType: createdCase.caseType, priority: createdCase.priority, source: "ai_pipeline" },
    actorUserId: null,
  });

  await db.insert(caseIncident).values({ caseId: createdCase.id, incidentId: createdIncident.id }).onConflictDoNothing();

  await recordCaseEvent({
    caseId: createdCase.id,
    eventType: "INCIDENT_LINKED",
    summary: `Incident ${createdIncident.incidentNumber} linked to case`,
    payload: { incidentId: createdIncident.id },
    actorUserId: null,
  });

  const [createdAlert] = await db
    .insert(alert)
    .values({
      alertType: input.eventType,
      title,
      message: description,
      severity,
      sourceDomain: "ai_pipeline",
      sourceEntityType: "CASE",
      sourceEntityId: createdCase.id,
      location: input.location ?? {},
      metadata: {
        targetRole: "ALL",
        cameraId: input.cameraId,
        confidence: input.confidence,
        caseId: createdCase.id,
        caseNumber: createdCase.caseNumber,
        incidentId: createdIncident.id,
        eventId: input.eventId,
        ...input.metadata,
      },
    })
    .returning();
  if (!createdAlert) {
    throw new Error("Alert was not created");
  }

  const recipientIds = await resolveAiAlertRecipientIds();
  if (recipientIds.length > 0) {
    const now = new Date();
    await db.insert(notification).values(
      recipientIds.map((recipientUserId) => ({
        alertId: createdAlert.id,
        recipientUserId,
        channel: "IN_APP",
        title: createdAlert.title,
        body: createdAlert.message,
        deliveryStatus: "DELIVERED",
        sentAt: now,
        deliveredAt: now,
      })),
    );
  }

  // After the alert, not before: operators are notified as soon as the
  // docket exists, and the images land on it moments later.
  const evidenceIds = await attachAiEvidence(createdCase.id, input, createdIncident.id);

  await recordAuditEvent({
    eventType: "ai.event_ingested",
    domain: "ai_pipeline",
    actorId: null,
    targetEntityType: "CASE",
    targetEntityId: createdCase.id,
    action: "CREATE",
    payload: {
      eventType: input.eventType,
      eventId: input.eventId,
      cameraId: input.cameraId,
      confidence: input.confidence,
      incidentId: createdIncident.id,
      alertId: createdAlert.id,
      evidenceIds,
    },
  });

  return { incident: createdIncident, case: createdCase, alert: createdAlert, evidenceIds, duplicate: false };
}
