import {
  bigint,
  index,
  integer,
  jsonb,
  numeric,
  pgTable,
  text,
  timestamp,
  uuid,
} from "drizzle-orm/pg-core";

export const mediaAsset = pgTable(
  "media_asset",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    type: text("type").notNull(),
    title: text("title").notNull(),
    description: text("description"),
    source: text("source").notNull(),
    sourceCameraId: text("source_camera_id"),
    originalFilename: text("original_filename").notNull(),
    mimeType: text("mime_type").notNull(),
    fileSize: bigint("file_size", { mode: "number" }).notNull(),
    fileHash: text("file_hash").notNull().unique(),
    storageUrl: text("storage_url").notNull(),
    storageTier: text("storage_tier").default("HOT").notNull(),
    duration: integer("duration"),
    resolution: text("resolution"),
    codec: text("codec"),
    framerate: numeric("framerate"),
    gpsLatitude: numeric("gps_latitude"),
    gpsLongitude: numeric("gps_longitude"),
    status: text("status").default("PROCESSING").notNull(),
    metadata: jsonb("metadata").default({}).notNull(),
    createdByUserId: text("created_by_user_id"),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (table) => [
    index("media_asset_type_idx").on(table.type),
    index("media_asset_source_idx").on(table.source),
    index("media_asset_created_at_idx").on(table.createdAt),
  ],
);
